from snakemake.utils import min_version

##### set minimum snakemake version #####
#min_version("6.4.1")


##### setup report #####
configfile: "config/config.yaml"


#report: "report/workflow.rst"


##### setup singularity #####

# this container defines the underlying OS for each job when using the workflow
# with --use-conda --use-singularity
#container: "docker://continuumio/miniconda3"


##### load rules #####


include: "rules/common.smk"
#include: "rules/get_loom.smk"
include: "rules/prepare_expression_h5ad.smk"
##include: "rules/run_scpopcorn.smk"
##include: "rules/integrate_scpopcorn_results.smk"
include: "rules/sexbias.smk"
##include: "rules/markers.smk"
#include: "rules/extract_ribosomal_expr.smk"


print(get_final_output())


##### target rules #####


rule all:
    input:
        get_final_output(),
